# Generated by Django 6.0 on 2026-03-07 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_dele_3bba04_idx',
        ),
    ]
