# Generated by Django 5.2.7 on 2026-04-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PAUSED', 'Paused'), ('OUT_OF_STOCK', 'Out of stock'), ('REJECTED', 'Rejected'), ('RESERVED', 'Reserved')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
