# Generated by Django 5.2.7 on 2026-04-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_pimages_date_created_alter_pimages_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcomments',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
