# Generated by Django 6.0 on 2026-03-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_products_pr_is_dele_3bba04_idx'),
        ('vendors', '0002_vendor_created_at_vendor_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('OUT_OF_STOCK', 'Out of stock'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor'], name='products_vendor_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_status_idx'),
        ),
    ]
