# Generated by Django 5.2.7 on 2026-03-27 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pimages',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='pimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
        ),
        migrations.AlterField(
            model_name='pimages',
            name='url_image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterModelTable(
            name='pimages',
            table='products_pimages',
        ),
    ]
