# Generated by Django 6.0 on 2026-04-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_status'),
        ('products', '0004_pcomments_is_edited'),
    ]

    operations = [
    ]
