# Generated by Django 6.0 on 2026-03-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_status_alter_product_description_and_more'),
        ('vendors', '0002_vendor_created_at_vendor_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_deleted'], name='products_is_deleted_idx'),
        ),
    ]
