# Generated by Django 5.2.7 on 2026-04-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PComments',
        ),
    ]
