# Generated by Django 6.0 on 2026-03-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_is_deleted_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
