# Generated by Django 5.2.7 on 2026-04-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_description_category_emoji_category_price'),
        ('products', '0006_delete_pcomments'),
    ]

    operations = [
    ]
