# Generated by Django 5.2.7 on 2026-04-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_merge_20260409_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='price',
        ),
    ]
