# Generated by Django 5.2.7 on 2026-04-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_category_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pimages',
            name='url_image',
            field=models.ImageField(upload_to='products/images/'),
        ),
    ]
