# Generated by Django 5.2.7 on 2026-04-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_pimages_url_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PAUSED', 'Paused'), ('OUT_OF_STOCK', 'Out of stock'), ('REJECTED', 'Rejected'), ('RESERVED', 'Reserved')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
