# Generated by Django 5.2.7 on 2026-04-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
