# Generated by Django 5.2.7 on 2026-04-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
