# Generated by Django 5.2.7 on 2026-04-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_ai_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pimages',
            name='is_moderated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='pimages',
            name='moderation_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pimages',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('FLAGGED', 'Marcado para revisión')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
