# Generated by Django 5.2.7 on 2026-04-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_pimages_is_moderated_pimages_moderation_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_status',
            field=models.CharField(choices=[('NONE', 'Ninguno'), ('PENDING', 'En cola'), ('PROCESSING', 'Procesando IA'), ('DONE', 'Completado'), ('FAILED', 'Error')], db_index=True, default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pimages',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('FLAGGED', 'Marcado para revisión')], db_index=True, default='APPROVED', max_length=20),
        ),
    ]
