# Generated by Django 5.2.7 on 2026-04-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pimages',
            name='url_image',
            field=models.TextField(),
        ),
    ]
