# Generated by Django 5.2.7 on 2026-04-29 22:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reserved_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reserved_by',
        ),
        # Reemplazamos el AlterField estándar por uno con casting manual
        migrations.RunSQL(
            sql="ALTER TABLE products_product ALTER COLUMN id TYPE uuid USING (lpad(id::text, 32, '0')::uuid);",
            reverse_sql='ALTER TABLE products_product ALTER COLUMN id TYPE bigint USING (id::text::bigint);'
        ),
        # Luego le decimos a Django que el campo ahora es un UUIDField
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('AVAILABLE', 'Available'), ('INACTIVE', 'Inactive'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
