# Generated by Django 5.2.7 on 2026-04-29 22:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reserved_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reserved_by',
        ),
        # Migration robusta para cambiar BigInt a UUID en PostgreSQL manejando dependencias
        migrations.RunSQL(
            sql="""
                -- 1. Eliminar la propiedad IDENTITY si existe (evita el error de tipo de columna identity)
                ALTER TABLE products_product ALTER COLUMN id DROP IDENTITY IF EXISTS;

                -- 2. Eliminar restricciones de llave foránea que apuntan a products_product(id)
                ALTER TABLE products_images DROP CONSTRAINT IF EXISTS products_pimages_products_product_id_a0da276c_fk_products_;
                ALTER TABLE orders_order DROP CONSTRAINT IF EXISTS orders_order_product_id_096244de_fk_products_product_id;
                ALTER TABLE moderation_flag DROP CONSTRAINT IF EXISTS moderation_flag_product_id_f295b1d2_fk_products_product_id;
                ALTER TABLE chat_ai_recommendation_event DROP CONSTRAINT IF EXISTS chat_ai_recommendati_product_id_450f1b63_fk_products_;

                -- 3. Cambiar el tipo de la columna ID en la tabla principal (con casting compatible)
                ALTER TABLE products_product ALTER COLUMN id TYPE uuid USING (lpad(id::text, 32, '0')::uuid);

                -- 4. Cambiar el tipo de las columnas de llave foránea en las tablas relacionadas
                ALTER TABLE products_images ALTER COLUMN products_product_id TYPE uuid USING (lpad(products_product_id::text, 32, '0')::uuid);
                ALTER TABLE orders_order ALTER COLUMN product_id TYPE uuid USING (lpad(product_id::text, 32, '0')::uuid);
                ALTER TABLE moderation_flag ALTER COLUMN product_id TYPE uuid USING (lpad(product_id::text, 32, '0')::uuid);
                ALTER TABLE chat_ai_recommendation_event ALTER COLUMN product_id TYPE uuid USING (lpad(product_id::text, 32, '0')::uuid);

                -- 5. Recrear las restricciones de llave foránea
                ALTER TABLE products_images ADD CONSTRAINT products_pimages_products_product_id_fk_products_product_id 
                    FOREIGN KEY (products_product_id) REFERENCES products_product(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
                ALTER TABLE orders_order ADD CONSTRAINT orders_order_product_id_fk_products_product_id 
                    FOREIGN KEY (product_id) REFERENCES products_product(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
                ALTER TABLE moderation_flag ADD CONSTRAINT moderation_flag_product_id_fk_products_product_id 
                    FOREIGN KEY (product_id) REFERENCES products_product(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
                ALTER TABLE chat_ai_recommendation_event ADD CONSTRAINT chat_ai_recommendation_event_product_id_fk_products_product_id 
                    FOREIGN KEY (product_id) REFERENCES products_product(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
                ALTER TABLE products_images DROP CONSTRAINT IF EXISTS products_pimages_products_product_id_fk_products_product_id;
                ALTER TABLE orders_order DROP CONSTRAINT IF EXISTS orders_order_product_id_fk_products_product_id;
                ALTER TABLE moderation_flag DROP CONSTRAINT IF EXISTS moderation_flag_product_id_fk_products_product_id;
                ALTER TABLE chat_ai_recommendation_event DROP CONSTRAINT IF EXISTS chat_ai_recommendation_event_product_id_fk_products_product_id;

                ALTER TABLE products_product ALTER COLUMN id TYPE bigint USING (id::text::bigint);
                ALTER TABLE products_images ALTER COLUMN products_product_id TYPE bigint USING (products_product_id::text::bigint);
                ALTER TABLE orders_order ALTER COLUMN product_id TYPE bigint USING (product_id::text::bigint);
                ALTER TABLE moderation_flag ALTER COLUMN product_id TYPE bigint USING (product_id::text::bigint);
                ALTER TABLE chat_ai_recommendation_event ALTER COLUMN product_id TYPE bigint USING (product_id::text::bigint);

                ALTER TABLE products_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            """
        ),
        # Luego le decimos a Django que el campo ahora es un UUIDField
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('AVAILABLE', 'Available'), ('INACTIVE', 'Inactive'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
