# Generated by Django 5.2.7 on 2026-05-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_product_reserved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('AVAILABLE', 'Available'), ('INACTIVE', 'Inactive'), ('REJECTED', 'Rejected'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
