# Generated by Django 5.2.7 on 2026-05-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_migrate_categories_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pimages',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('FLAGGED', 'Marcado para revision')], db_index=True, default='APPROVED', max_length=20),
        ),
    ]
