# Generated by Django on 2026-05-15 - Remove category FK after M2M migration

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_migrate_categories_data'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE products_product DROP COLUMN IF EXISTS category_id;',
                    reverse_sql='ALTER TABLE products_product ADD COLUMN category_id integer NULL;'
                )
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='product',
                    name='category',
                ),
            ]
        )
    ]
