# Generated by Django 5.2.7 on 2026-05-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_pimages_moderation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
