# Generated by Django 5.2.7 on 2026-05-20 18:39

from django.db import migrations

def drop_column_safely(apps, schema_editor):
    db_engine = schema_editor.connection.vendor
    
    # Si estamos en Railway (PostgreSQL), ejecutamos con IF EXISTS seguro
    if db_engine == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('ALTER TABLE products_product DROP COLUMN IF EXISTS category_id;')
            
    # Si estamos en Local (SQLite), validamos primero si existe la columna para que no rompa
    elif db_engine == 'sqlite':
        cursor = schema_editor.connection.cursor()
        table_fields = [f.name for f in schema_editor.connection.introspection.get_table_description(
            cursor, 'products_product'
        )]
        if 'category_id' in table_fields:
            # Si todavía existía en tu SQLite local, la borramos usando el motor nativo
            Product = apps.get_model('products', 'Product')
            field = Product._meta.get_field('category')
            schema_editor.remove_field(Product, field)

class Migration(migrations.Migration):

    dependencies = [
        # Mantenemos la dependencia de tu última migración exitosa
        ('products', '0024_alter_pimages_moderation_status'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # 1. Base de datos: Corre la función inteligente según el motor (Postgres/SQLite)
            database_operations=[
                migrations.RunPython(drop_column_safely)
            ],
            # 2. Estado de Django: Remueve el campo definitivamente para el ORM
            state_operations=[
                migrations.RemoveField(
                    model_name='product',
                    name='category',
                ),
            ]
        )
    ]