# Generated by Django on 2026-05-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_pimages_moderation_status'),
        ('products', '0024_product_remove_category'),
    ]

    operations = [
    ]
