# Generated by Django on 2026-05-15 - Remove category FK after M2M migration

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_pimages_moderation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]