# Generated by Django 6.0 on 2026-03-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = []
