# Generated by Django 5.2.7 on 2026-05-13 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'terms_acceptance',
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['user', 'version'], name='terms_user_version_idx'), models.Index(fields=['accepted_at'], name='terms_accepted_at_idx')],
            },
        ),
    ]
