# Generated by Django 5.2.7 on 2026-05-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'terms_content',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['version', 'is_active'], name='terms_content_active_idx')],
            },
        ),
    ]
