# Generated by Django 5.2.7 on 2026-04-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('reason', models.TextField(help_text='Razón del bloqueo')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Si está vacío, el bloqueo es permanente', null=True)),
            ],
            options={
                'verbose_name': 'IP Bloqueada',
                'verbose_name_plural': 'IPs Bloqueadas',
                'db_table': 'core_banned_ip',
            },
        ),
    ]
