# Generated by Django 5.2.7 on 2026-04-30 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_initial'),
        ('products', '0020_remove_product_reserved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejected_images_count', models.PositiveIntegerField(default=0)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pendiente revisión'), ('REVIEWED', 'Revisado'), ('APPROVED_PRODUCT', 'Producto aprobado'), ('REJECTED_PRODUCT', 'Producto rechazado completamente'), ('APPROVED_IMAGES', 'Solo imágenes aprobadas')], db_index=True, default='PENDING', max_length=30)),
                ('admin_notes', models.TextField(blank=True, help_text='Razones por las que se rechaza/aprueba el producto completo')),
                ('content_issues', models.JSONField(blank=True, help_text="{'name': bool, 'description': bool, 'images': bool, ...}", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_record', to='products.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_products', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderation_product_review',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['review_status', '-created_at'], name='moderation__review__91476e_idx'), models.Index(fields=['vendor'], name='moderation__vendor__148f4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='RejectedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_reason', models.TextField()),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pendiente revisión'), ('REVIEWED', 'Revisado por admin'), ('APPROVED', 'Aprobado por admin'), ('CONFIRMED_REJECTED', 'Rechazo confirmado')], db_index=True, default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_record', to='products.pimages')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_images', to='products.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rejected_images', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_product_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderation_rejected_image',
                'ordering': ['-rejected_at'],
                'indexes': [models.Index(fields=['review_status', '-rejected_at'], name='moderation__review__b9ebb6_idx'), models.Index(fields=['vendor'], name='moderation__vendor__a20b43_idx')],
            },
        ),
    ]
