# Generated by Django 5.2.7 on 2026-04-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reputation_score',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
