# Generated by Django 5.2.7 on 2026-04-12 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_reputation_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='expedition_date',
        ),
    ]
