# Generated by Django 5.2.7 on 2026-04-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_expedition_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acepto_terminos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_aceptacion_terminos',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
