# Generated by Django 5.2.7 on 2026-04-22 18:33

import apps.core.utils.encryption
from django.db import migrations


def encrypt_existing_users(apps, schema_editor):
    from apps.core.utils.encryption import EncryptionService
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        changed = False
        if user.full_name and not user.full_name.startswith('gAAAA'):
             user.full_name = EncryptionService.encrypt(user.full_name)
             changed = True
        if user.phone_number and not user.phone_number.startswith('gAAAA'):
             user.phone_number = EncryptionService.encrypt(user.phone_number)
             changed = True
        if user.document_number and not user.document_number.startswith('gAAAA'):
             user.document_number = EncryptionService.encrypt(user.document_number)
             changed = True
        if user.birth_date and not user.birth_date.startswith('gAAAA'):
             user.birth_date = EncryptionService.encrypt(str(user.birth_date))
             changed = True
        
        if changed:
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_setup_initial_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=apps.core.utils.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_number',
            field=apps.core.utils.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=apps.core.utils.encryption.EncryptedCharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=apps.core.utils.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(encrypt_existing_users, reverse_code=migrations.RunPython.noop),
    ]
