# Generated by Django 5.2.7 on 2026-04-27 20:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_encrypt_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt_key',
            field=models.UUIDField(default=uuid.uuid4, help_text='Cambiar este valor invalida todos los access tokens del usuario.'),
        ),
    ]
