# Generated by Django 5.2.7 on 2026-04-01 00:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACTIVE', 'Activo'), ('BLOCKED', 'Bloqueado')], db_index=True, default='PENDING', max_length=20)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('location_type', models.CharField(choices=[('FIXED', 'Fijo'), ('MOBILE', 'Móvil')], default='FIXED', max_length=10)),
                ('reputation', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vendors_vendorprofile',
                'indexes': [models.Index(fields=['status'], name='vendors_ven_status_e0f104_idx'), models.Index(fields=['verified'], name='vendors_ven_verifie_f728fc_idx')],
            },
        ),
    ]
