# Generated by Django 6.0 on 2026-03-25 03:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACTIVE', 'Activo'), ('BLOCKED', 'Bloqueado')], db_index=True, default='PENDING', max_length=20)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('location_type', models.CharField(choices=[('FIXED', 'Fijo'), ('MOBILE', 'Móvil')], default='FIXED', max_length=10)),
                ('reputation', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='vendors_ven_status_2dcb2a_idx'), models.Index(fields=['verified'], name='vendors_ven_verifie_775df7_idx')],
            },
        ),
    ]
