# Generated by Django 6.0 on 2026-03-07 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendor_user'),
    ]

    operations = []
