# Generated by Django 5.2.7 on 2026-04-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vendors.vendorprofile',),
        ),
    ]
