# Generated by Django 5.2.7 on 2026-04-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='timestamp',
        ),
    ]
