# Generated by Django 6.0 on 2026-03-03 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_remove_auditlog_audit_audit_created_2c1626_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_user_id_292c79_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_content_4c2ead_idx',
        ),
    ]
