# Generated by Django 5.2.7 on 2026-04-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditlog_is_suspicious_auditlog_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SOFT_DELETE', 'Soft Delete'), ('RESTORE', 'Restore'), ('STATUS_CHANGE', 'Status Change'), ('ROLE_CHANGE', 'Role Change'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REFRESH', 'Refresh'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50),
        ),
    ]
