# Generated by Django 6.0 on 2026-03-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_add_hu04_required_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_content_4c2ead_idx',
            old_name='audit_ct_obj_idx',
        ),
    ]
