# Generated by Django 5.2.7 on 2026-04-08 20:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_client_remove_order_vendor_and_more'),
        ('reviews', '0003_remove_review_client_remove_review_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('order', 'user')},
        ),
    ]
