# Generated by Django 5.2.7 on 2026-04-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_vendorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorProfile',
        ),
    ]
