# Generated by Django 5.2.7 on 2026-04-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_delete_vendorprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='vendor',
            new_name='user',
        ),
    ]
