# Generated by Django 5.2.7 on 2026-04-09 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_alter_location_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LImages',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url_image', models.TextField()),
                ('is_main', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='geo.location')),
            ],
            options={
                'db_table': 'locations_images',
            },
        ),
    ]
