# Generated by Django 5.2.7 on 2026-04-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0009_limages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limages',
            name='url_image',
            field=models.ImageField(upload_to='locations/images/'),
        ),
    ]
