# Generated by Django 5.2.7 on 2026-04-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0010_alter_limages_url_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
