# Generated by Django 5.2.7 on 2026-04-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=18, max_digits=21),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=18, max_digits=21),
        ),
    ]
