# Generated by Django 5.2.7 on 2026-04-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0012_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limages',
            name='url_image',
            field=models.TextField(),
        ),
    ]
