# Generated by Django 5.2.7 on 2026-04-16 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0012_product_ai_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('user_query', models.TextField(help_text="La frase o contexto que el usuario proveyó (ej: 'busco zapatillas baratas').")),
                ('ai_reasoning', models.TextField(blank=True, help_text='Opcional. Explicación breve de por qué la IA recomendó esto.', null=True)),
                ('buyer', models.ForeignKey(blank=True, help_text='El comprador que chateó con el asistente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='El producto recomendado.', on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='products.product')),
            ],
            options={
                'db_table': 'chat_ai_recommendation_event',
                'indexes': [models.Index(fields=['product'], name='chat_ai_rec_product_31ce04_idx'), models.Index(fields=['buyer'], name='chat_ai_rec_buyer_i_70047f_idx')],
            },
        ),
    ]
